frr version 10.4.1
frr defaults traditional
hostname r1
log syslog informational
!
interface Ethernet0
 ipv6 address 2001:db8:12::1/64
!
interface Loopback0
 ip address 10.0.0.1/32
 ipv6 address 2001:db8:1::1/128
!
ipv6 forwarding
ip forwarding
!
router bgp 65001
 bgp router-id 10.0.0.1
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 2001:db8:12::2 remote-as 65002
 neighbor 2001:db8:12::2 description r2
 !
 address-family ipv6 unicast
  network 2001:db8:1::1/128
  network fc00:0:1::/48
  neighbor 2001:db8:12::2 activate
  neighbor 2001:db8:12::2 next-hop-self
  neighbor 2001:db8:12::2 soft-reconfiguration inbound
 exit-address-family
!
exit
!
end