frr version 10.4.1
frr defaults traditional
hostname r3
log syslog informational
!
interface Ethernet0
 ipv6 address 2001:db8:53::3/64
!
interface Ethernet4
 ipv6 address 2001:db8:34::3/64
!
interface Loopback0
 ip address 10.0.0.3/32
 ipv6 address 2001:db8:3::1/128
!
ipv6 forwarding
ip forwarding
!
router bgp 65003
 bgp router-id 10.0.0.3
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 2001:db8:53::5 remote-as 65005
 neighbor 2001:db8:53::5 description rn
 !
 neighbor 2001:db8:34::4 remote-as 65004
 neighbor 2001:db8:34::4 description r4
 !
 address-family ipv6 unicast
  network 2001:db8:3::1/128
  network fc00:0:3::/48
  neighbor 2001:db8:53::5 activate
  neighbor 2001:db8:53::5 next-hop-self
  neighbor 2001:db8:53::5 soft-reconfiguration inbound
  neighbor 2001:db8:34::4 activate
  neighbor 2001:db8:34::4 next-hop-self
  neighbor 2001:db8:34::4 soft-reconfiguration inbound
 exit-address-family
!
exit
!
end