frr version 10.4.1
frr defaults traditional
hostname r4
log syslog informational
!
interface Ethernet0
 ipv6 address 2001:db8:34::4/64
!
interface Loopback0
 ip address 10.0.0.4/32
 ipv6 address 2001:db8:4::1/128
!
ipv6 forwarding
ip forwarding
!
router bgp 65004
 bgp router-id 10.0.0.4
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 2001:db8:34::3 remote-as 65003
 neighbor 2001:db8:34::3 description r3
 !
 address-family ipv6 unicast
  network 2001:db8:4::1/128
  network fc00:0:4::/48
  network 2001:db8:99::4/128
  neighbor 2001:db8:34::3 activate
  neighbor 2001:db8:34::3 next-hop-self
  neighbor 2001:db8:34::3 soft-reconfiguration inbound
 exit-address-family
!
exit
!
end