frr version 10.4.1
frr defaults traditional
hostname rn
log syslog informational
!
interface Ethernet0
 ipv6 address 2001:db8:25::5/64
!
interface Ethernet4
 ipv6 address 2001:db8:53::5/64
!
interface Loopback0
 ip address 10.0.0.5/32
 ipv6 address 2001:db8:5::1/128
!
ipv6 forwarding
ip forwarding
!
router bgp 65005
 bgp router-id 10.0.0.5
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 !
 neighbor 2001:db8:25::2 remote-as 65002
 neighbor 2001:db8:25::2 description r2
 !
 neighbor 2001:db8:53::3 remote-as 65003
 neighbor 2001:db8:53::3 description r3
 !
 address-family ipv6 unicast
  network 2001:db8:5::1/128
  network fc00:0:5::/48
  neighbor 2001:db8:25::2 activate
  neighbor 2001:db8:25::2 next-hop-self
  neighbor 2001:db8:25::2 soft-reconfiguration inbound
  neighbor 2001:db8:53::3 activate
  neighbor 2001:db8:53::3 next-hop-self
  neighbor 2001:db8:53::3 soft-reconfiguration inbound
 exit-address-family
!
exit
!
end